Create Arduino Library
victorhurdugaci/SerialProtocol pull request #3
Opened 2018-09-05 05:34 UTC by headHUB

Thank you for this software!  It works perfectly.  I am new to writing software so I wanted to contribute.  I took the repository and made it into an Arduino library so it can be downloaded as a zip file and installed through Arduino menu.  I also moved the sample arduino file so that it can ba accessed from the file menu.  I am in the middle of writing two more examples and will upload when done.

2018-09-23 02:47 UTC, headHUB commented
hello?

2018-09-30 18:34 UTC, victorhurdugaci commented
> hello?

Sorry, I was on vacation :) I'm back now

2018-09-30 18:44 UTC, victorhurdugaci requested changes
Hey @headHUB congratulations on your first contribution! 👏 

I left a few comments but overall the change looks good. Let me know when you addressed them and I take another look

2018-09-30 18:44 UTC, victorhurdugaci commented on README.MD
> +Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
Can you please add a new section at the end of this file called "Contributors" and add your name to it?

2018-09-30 18:44 UTC, victorhurdugaci commented on keywords.txt
> +
nitpick: there's an empty line here after `####` but no in the other sections

2018-09-30 18:44 UTC, victorhurdugaci commented on README.MD
> +Download the Repository, Go to Sketch>Include Library>Add .zip Library> Select the Downloaded .zip File.
can you please make this a bit more explicit by saying "Download the repository as zip"? Someone might get confused by it and just git clone it.

Also nitpick on this line. `>` follow by spaces in some cases but not in others (consistency)

2018-09-30 18:44 UTC, victorhurdugaci commented on README.MD
I don't think the `samples` folder exist anymore in your change, right? Can you also update this part of the readme?

2018-09-30 18:44 UTC, victorhurdugaci commented on extras/raspberry_app/makefile
> +g++ -I$(SERIAL_PROTOCOL_DIR) $(CPP_SOURCES) -o $(TARGET)
Why did you remove the indentation?

2018-10-14 05:21 UTC, headHUB commented on README.MD
> +Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
I have completed this.  A github user per1234 contributed to my branch so should I include them as a contributor here?  I have no contact information except http://github.com/per1234.

2018-10-14 05:21 UTC, headHUB commented on README.MD
I rewrote this whole section to be more user friendly.

2018-10-14 05:23 UTC, headHUB commented
Now that I have made changes and committed to my branch, should I create a new request?  I've never done this before.  This is the first chance I have been able to help with this sort of thing.

2018-10-14 05:25 UTC, headHUB commented on README.MD
> +Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
I also suggest renaming repository to ArduinoSerialProtocol.  When you do I can adjust the readme to match

2018-10-14 23:23 UTC, victorhurdugaci commented on README.MD
> +Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
I'll leave the repository name like this for now

2018-10-14 23:24 UTC, victorhurdugaci approved these changes

2018-10-14 23:25 UTC, merged

2018-10-14 23:25 UTC, victorhurdugaci commented
Congratulations on merging your first PR :)

2018-10-14 23:30 UTC, headHUB commented
Thank you.  Ive borrowed so much code from so many places, I'm glad to be able to give back a little.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Victor Hurdugaci <notifications@github.com>
Sent: Sunday, October 14, 2018 6:25:39 PM
To: victorhurdugaci/SerialProtocol
Cc: James Head; Mention
Subject: Re: [victorhurdugaci/SerialProtocol] Create Arduino Library (#3)


Congratulations on merging your first PR :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/victorhurdugaci/SerialProtocol/pull/3#issuecomment-429672357>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Ab6XJP9TpQtri68EzR8LzK-9wMDuSlbuks5uk8fzgaJpZM4WaNfE>.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/victorhurdugaci/SerialProtocol","title":"victorhurdugaci/SerialProtocol","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/victorhurdugaci/SerialProtocol"}},"updates":{"snippets":[{"icon":"PERSON","message":"@victorhurdugaci in #3: Congratulations on merging your first PR :)"}],"action":{"name":"View Pull Request","url":"https://github.com/victorhurdugaci/SerialProtocol/pull/3#issuecomment-429672357"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/victorhurdugaci/SerialProtocol/pull/3#issuecomment-429672357", "url": "https://github.com/victorhurdugaci/SerialProtocol/pull/3#issuecomment-429672357", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [victorhurdugaci/SerialProtocol] Create Arduino Library (#3)", "sections": [ { "text": "", "activityTitle": "**Victor Hurdugaci**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@victorhurdugaci", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"victorhurdugaci/SerialProtocol\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "targets": [ { "os": "default", "uri": "https://github.com/victorhurdugaci/SerialProtocol/pull/3#issuecomment-429672357" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 375969732\n}" } ], "themeColor": "26292E" } ]